#!/bin/sh

set -euC

# Container name for redmined. If not set, use "redmined-container" as default.
readonly CONTAINER_NAME=${REDMINED_CONTAINER_NAME:-"redmined-container"}

# Whether to map the UID and GID of the host user to the container user. If not set, do not map.
readonly MAP_HOST_USER_TO_CONTAINER_USER=${REDMINED_MAP_HOST_USER_TO_CONTAINER_USER:-""}

# Volume name for bundler cache. If not set, use "redmine-bundle-cache" as default.
readonly BUNDLE_CACHE_VOLUME=${REDMINED_BUNDLE_CACHE_VOLUME:-"redmine-bundle-cache"}

# Docker image for redmined. If not set, use "ghcr.io/hidakatsuya/redmined" as default.
readonly IMAGE=${REDMINED_IMAGE:-"ghcr.io/hidakatsuya/redmined"}

# Port mapping for Redmine. If not set, use "3000:3000" as default.
readonly PUBLISH_PORT=${REDMINED_PUBLISH_PORT:-"3000:3000"}


docker_run() {
  local user_option=""

  if [ -n "$MAP_HOST_USER_TO_CONTAINER_USER" ]; then
    user_option="-e USER_ID=$(id -u) -e GROUP_ID=$(id -g)"
  fi

  docker run --name $CONTAINER_NAME --rm -it \
     $user_option \
    -v ${PWD}:/redmine \
    -v $BUNDLE_CACHE_VOLUME:/bundle \
    -p $PUBLISH_PORT \
    $IMAGE "$@"
}

docker_exec() {
  local user_option=""

  if [ -n "$MAP_HOST_USER_TO_CONTAINER_USER" ]; then
    user_option="--user $(id -u):$(id -g)"
  fi

  docker exec -it $user_option $CONTAINER_NAME "$@"
}

container_running() {
  docker ps -q --filter name=$CONTAINER_NAME
}

main() {
  if [ ! $(container_running) ]; then
    docker_run "$@"
  else
    docker_exec "$@"
  fi
}


main "$@"

