#!/usr/bin/env bash

set -euC

# Experimental: Whether to use Apple container. If not set, do not use Apple container.
USE_APPLE_CONTAINER=${REDMINED_USE_APPLE_CONTAINER:-""}

# Container name for redmined. If not set, use "redmined-container" as default.
CONTAINER_NAME=${REDMINED_CONTAINER_NAME:-"redmined-container"}

# Whether to map the UID and GID of the host user to the container user. If not set, do not map.
MAP_HOST_USER_TO_CONTAINER_USER=${REDMINED_MAP_HOST_USER_TO_CONTAINER_USER:-""}

# Volume name for bundler cache. If not set, use "redmine-bundle-cache" as default.
BUNDLE_CACHE_VOLUME=${REDMINED_BUNDLE_CACHE_VOLUME:-"redmined-bundle-cache"}

# Ruby version for redmined. If not set, use "" as default.
IMAGE_RUBY_VERSION=${REDMINED_RUBY:-""}

# Docker image for redmined. If not set, use "ghcr.io/hidakatsuya/redmined" as default.
IMAGE=${REDMINED_IMAGE:-"ghcr.io/hidakatsuya/redmined"}

# Port number for Redmine. If not set, use "3000" as default.
REDMINE_PORT=${REDMINED_REDMINE_PORT:-"3000"}

# Port number for publishing container port to host. If not set, use "$REDMINE_PORT:$REDMINE_PORT" as default.
PUBLISH_PORT=${REDMINED_PUBLISH_PORT:-""}

# Environment variables passed to the container. Multiple variables should be separated by space. If not set, use "" as default.
CONTAINER_ENVS=${REDMINED_CONTAINER_ENVS:-""}

# Configuration file for redmined
CONFIG_FILE=${REDMINED_CONFIG_FILE:-".redmined.json"}

# Platform for the Docker image. If not set, use "" as default.
PLATFORM=${REDMINED_PLATFORM:-""}

# Whether to run the container in non-TTY mode. If not set, disable non-TTY mode.
# No TTY mode is also enabled by `-T` opeion of redmined command.
NO_TTY=${REDMINED_NO_TTY:-""}

# Network for the Docker container. If not set, use "" as default.
NETWORK=${REDMINED_NETWORK:-""}

# This must be the same as the user name in the Dockerfile
readonly CONTAINER_USER="developer"

# Which Docker command to use, docker or container. If not set, CONTAINER_CMD="docker"
if [ -n "$USE_APPLE_CONTAINER" ]; then
    readonly CONTAINER_CMD="container"
else
    readonly CONTAINER_CMD="docker"
fi


exit_with_usage() {
    cat <<'EOS' 1>&2
Usage: redmined [options] [command]

Command:
  Commands to run in the container

Options:
  -n NAME  Specify the configuration name to load from the configuration file
  -T       Run the commands in non-TTY mode
  -c       Print the contents of the configuration file
  -u       Update the redmined script itself and the redmined images to the latest version
  -d       Create a SQLite database configuration file

Examples:
  Run commands in the container.
  $ redmined ruby -v
  ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]

  $ redmined bundle install
  Fetching gem metadata from https://rubygems.org/...
  ...

  Enter the container through the bash shell.
  $ redmined bash
  developer@7cc80c9cd1f7:/redmine$

  Launch the Redmine server.
  $ redmined bin/rails server
  => Booting Puma
  => Rails 7.2.1 application starting in development
  => Run `bin/rails server --help` for more startup options
  Puma starting in single mode...
  * Puma version: 6.4.2 (ruby 3.3.4-p94) ("The Eagle of Durango")
  *  Min threads: 0
  *  Max threads: 5
  *  Environment: development
  *          PID: 1
  * Listening on http://0.0.0.0:3000
  Use Ctrl-C to stop

  Run the comands on the "any-config" configuration in the .redmined.json.
  $ redmined -n any-config bundle show

  Run the commands in non-TTY mode.
  $ redmined -T bin/rails test

  Print the contents of the .redmined.json.
  $ redmined -c
  {
    "default": {
      "name": "redmica",
      "port": "3001"
    },
    "ruby3.2": {
      "name": "redmica-ruby3.2",
      "ruby": "3.2"
    }
  }

  Update the redmined script itself and the redmined images to the latest version.
  $ redmined -u
  Updating redmined...
  Installed redmined to /home/hidakatsuya/.local/bin

  Updating redmined images...
  ghcr.io/hidakatsuya/redmined:latest
  ghcr.io/hidakatsuya/redmined:ruby3.3
EOS
    exit 0
}

docker_run() {
    local user_option=""
    if [ -n "$MAP_HOST_USER_TO_CONTAINER_USER" ]; then
        user_option="-e USER_ID=$(id -u) -e GROUP_ID=$(id -g)"
    fi

    local platform_option=""
    if [ -n "$PLATFORM" ]; then
        if [ "$CONTAINER_CMD" = "container" ]; then
            platform_option="--arch $PLATFORM"
        else
            platform_option="--platform $PLATFORM"
        fi
    fi

    local tty_option=""
    if [ -z "$NO_TTY" ]; then
        tty_option="-it"
    fi

    local network_option=""
    if [ -n "$NETWORK" ]; then
        network_option="--network $NETWORK"
    fi

    if [ "$CONTAINER_CMD" = "container" ]; then
        # Apple container CLI does not support automatic volume creation.
        if ! container volume ls | grep -q $BUNDLE_CACHE_VOLUME; then
            container volume create $BUNDLE_CACHE_VOLUME
        fi
    fi

    $CONTAINER_CMD run --name $CONTAINER_NAME --rm \
        $tty_option \
        $user_option \
        $platform_option \
        $network_option \
        -v ${PWD}:/redmine \
        -v $BUNDLE_CACHE_VOLUME:/bundle \
        -p ${PUBLISH_PORT:-"$REDMINE_PORT:$REDMINE_PORT"} \
        -e PORT=$REDMINE_PORT \
        $(image_name) "$@"
}

docker_exec() {
    local user_option=""
    if [ -n "$MAP_HOST_USER_TO_CONTAINER_USER" ]; then
        user_option="--user $(id -u):$(id -g)"
    else
        user_option="--user $CONTAINER_USER"
    fi

    local tty_option=""
    if [ -z "$NO_TTY" ]; then
        tty_option="-it"
    fi

    $CONTAINER_CMD exec $tty_option $user_option $CONTAINER_NAME "$@"
}

image_name() {
    # "image:tag" > "image tag" > ["image", "tag"]
    local image_array=(${IMAGE//:/ })

    local image_name=${image_array[0]}
    local image_tag=${image_array[1]:-""}

    if [ -n "$IMAGE_RUBY_VERSION" ]; then
        echo "$image_name:${image_tag:-ruby$IMAGE_RUBY_VERSION}"
    else
        echo $IMAGE
    fi
}

container_running() {
    if [ "$CONTAINER_CMD" = "container" ]; then
        container ls -a | awk -v name="$CONTAINER_NAME" '$1 == name {print $1}'
    else
        docker ps --format "{{.Names}}" | grep -Fxq "$CONTAINER_NAME"
    fi
}

cd_redmine_root() {
    current_dir=$(pwd)

    while [ ! -f "Rakefile" ]; do
        cd ..
        if [ "$(pwd)" = "$current_dir" ]; then
            echo "No Redmine root directory found"
            exit 1
        fi
        current_dir=$(pwd)
    done
}

load_config() {
    target="${1:-"default"}"

    if [ ! -e $CONFIG_FILE ]; then
        return 0
    fi

    if ! command -v jq > /dev/null; then
        echo "[WARNING] Skipped loading configuration file because jq is not installed. Please install jq."
        return 0
    fi

    local name=$(jq -r --arg t $target '.[$t].name // ""' $CONFIG_FILE)
    if [ -n "$name" ]; then
        CONTAINER_NAME="redmined-container-$name"
        BUNDLE_CACHE_VOLUME="redmined-bundle-cache-$name"
    fi

    local img=$(jq -r --arg t $target '.[$t].image // ""' $CONFIG_FILE)
    if [ -n "$img" ]; then
        IMAGE="$img"
    fi

    local ruby=$(jq -r --arg t $target '.[$t].ruby // ""' $CONFIG_FILE)
    if [ -n "$ruby" ]; then
        IMAGE_RUBY_VERSION="$ruby"
    fi

    local env=$(jq -r --arg t $target '.[$t].env // {} | to_entries | map("\(.key)=\(.value)") | join(" ")' $CONFIG_FILE)
    if [ -n "$env" ]; then
        CONTAINER_ENVS="$env"
    fi

    local port=$(jq -r --arg t $target '.[$t].port // ""' $CONFIG_FILE)
    if [ -n "$port" ]; then
        REDMINE_PORT="$port"
    fi

    local platform=$(jq -r --arg t $target '.[$t].platform // ""' $CONFIG_FILE)
    if [ -n "$platform" ]; then
        PLATFORM="$platform"
    fi

    local network=$(jq -r --arg t $target '.[$t].network // ""' $CONFIG_FILE)
    if [ -n "$network" ]; then
        NETWORK="$network"
    fi
}

print_configuration() {
    if [ -e "$CONFIG_FILE" ]; then
      cat $CONFIG_FILE
    else
      echo "No configuration found"
    fi
    exit 0
}

update_redmined_and_images() {
    local install_file_url=https://raw.githubusercontent.com/hidakatsuya/redmined/main/install.sh
    local install_dir=$(dirname $(readlink -f $0))

    echo "Updating redmined..."

    if command -v wget > /dev/null; then
        wget -qO- $install_file_url | REDMINED_INSTALL_DIR=$install_dir sh
    elif command -v curl > /dev/null; then
        curl -sSL $install_file_url | REDMINED_INSTALL_DIR=$install_dir sh
    else
        echo  "Failed to update redmined: wget or curl is required."
        exit 1
    fi

    echo ""
    echo "Updating redmined images..."

    if [ "$CONTAINER_CMD" = "container" ]; then
        # Apple container CLI does not support --format, so use awk to extract repository:tag
        local images=$(container images ls $IMAGE | awk 'NR>1 {print $1 ":" $2}' | grep -v "<none>")

        for image in $images; do
            container images pull $image
        done
    else
        local images=$(docker images --format "{{.Repository}}:{{.Tag}}" $IMAGE | grep -v "<none>")

        for image in $images; do
            docker pull -q $image
        done
    fi

    exit 0
}

create_sqlite_database_config() {
    if [ -f "config/database.yml" ]; then
        echo "config/database.yml already exists."
        exit 0
    fi

    cat <<EOS > config/database.yml
development:
  adapter: sqlite3
  database: db/development.sqlite3
test:
  adapter: sqlite3
  database: db/test.sqlite3
production:
  adapter: sqlite3
  database: db/production.sqlite3
EOS
    echo "config/database.yml created."
    exit 0
}

main() {
    if [ "$#" -eq 0 ]; then
        exit_with_usage
    fi

    (
        cd_redmine_root

        local config_name=""
        while getopts ":n:Tcud" opt; do
            case $opt in
                n)    config_name=$OPTARG;;
                T)    NO_TTY=1;;
                c)    print_configuration;;
                u)    update_redmined_and_images;;
                d)    create_sqlite_database_config;;
                \?|:) exit_with_usage;;
            esac
        done
        # Remove options from arguments
        shift $((OPTIND - 1))

        load_config $config_name

        local envs=""
        if [ -n "$CONTAINER_ENVS" ]; then
            envs="env $CONTAINER_ENVS "
        fi

        if [ -z "$(container_running)" ]; then
            docker_run $envs "$@"
        else
            docker_exec $envs "$@"
        fi
    )
}

main "$@"
