name: Build and push redmined image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - ruby-version: "3.4"
            dockerfile: Dockerfile.bookworm
            tags: "ghcr.io/hidakatsuya/redmined:ruby3.4"

          - ruby-version: "3.4"
            dockerfile: Dockerfile
            tags: "ghcr.io/hidakatsuya/redmined:ruby3.4-trixie"

          - ruby-version: "4.0"
            dockerfile: Dockerfile.bookworm
            tags: "ghcr.io/hidakatsuya/redmined:ruby4.0,ghcr.io/hidakatsuya/redmined:latest"

          - ruby-version: "4.0"
            dockerfile: Dockerfile
            tags: "ghcr.io/hidakatsuya/redmined:ruby4.0-trixie"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      - uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: RUBY_VERSION=${{ matrix.ruby-version }}
          tags: ${{ matrix.tags }}
