name: Build and push redmined image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - ruby-version: "3.4"
            dockerfile: Dockerfile.bookwarm
            tags: "ghcr.io/hidakatsuya/redmined:ruby3.4,ghcr.io/hidakatsuya/redmined:latest"

          - ruby-version: "3.4"
            dockerfile: Dockerfile
            tags: "ghcr.io/hidakatsuya/redmined:ruby3.4-trixie"

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: RUBY_VERSION=${{ matrix.ruby-version }}
          tags: ${{ matrix.tags }}
