name: Build and publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "redmined"
      - "install.sh"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: ./.github/actions/test

  build-and-publish:
    needs: test

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - ruby-version: "3.3"
            tags: "ghcr.io/hidakatsuya/redmined:ruby3.3,ghcr.io/hidakatsuya/redmined:latest"
          - ruby-version: "3.2"
            tags: "ghcr.io/hidakatsuya/redmined:ruby3.2"

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: RUBY_VERSION=${{ matrix.ruby-version }}
          tags: ${{ matrix.tags }}
