name: Test and Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "install.sh"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      # This is for determining weather an Docker image need to be built or not on the next job.
      dockerfile-changed: ${{ contains(steps.changed-files.outputs.all_modified_files, 'Dockerfile') }}

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: ./.github/actions/test

      - uses: tj-actions/changed-files@v44
        id: changed-files

  build-and-publish:
    needs: test

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    if: ${{ needs.test.outputs.dockerfile-changed == 'true' }}

    strategy:
      matrix:
        include:
          - ruby-version: "3.3"
            tags: "ghcr.io/hidakatsuya/redmined:ruby3.3,ghcr.io/hidakatsuya/redmined:latest"
          - ruby-version: "3.2"
            tags: "ghcr.io/hidakatsuya/redmined:ruby3.2"

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: RUBY_VERSION=${{ matrix.ruby-version }}
          tags: ${{ matrix.tags }}
