name: Test and Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "install.sh"
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  check-need-to-build-image:
    runs-on: ubuntu-latest

    outputs:
      is-need: ${{ contains(steps.changed-files.outputs.all_modified_files, 'Dockerfile') }}

    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files

  build-and-publish:
    needs: [test, check-need-to-build-image]

    if: ${{ needs.check-need-to-build-image.outputs.is-need == 'true' }}

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/build.yml
