name: Test

on:
  push:
    branches:
      - dev/**
      - main
    paths-ignore:
      - "**.md"
  pull_request:

  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REDMINED_NO_TTY: 1
      REDMINED_IMAGE: redmined:test
      REDMINED_REDMINE_PORT: 3001
      REDMINED_CONTAINER_ENVS: RAILS_ENV=test

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      - uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: .
          load: true
          tags: redmined:test

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: redmine/redmine
          ref: master
          path: redmine1-src

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: redmine/redmine
          ref: master
          path: redmine2-src

      - name: Set up redmined
        run: |
          chmod +x redmined
          mkdir -p $HOME/.local/bin
          cp redmined $HOME/.local/bin
        shell: bash

      - name: Set up Redmine
        run: |
          cd $GITHUB_WORKSPACE/redmine1-src
          chmod a+w -R .

          # Create a config/database.yml
          redmined -d
          test -f config/database.yml

          cat <<EOS > config/configuration.yml
          default:
            minimagick_font_path: /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc
          EOS

          redmined bundle install
          redmined bin/rails db:prepare

          cd $GITHUB_WORKSPACE/redmine2-src
          chmod a+w -R .

          cat <<EOS > config/database.yml
          test:
            adapter: sqlite3
            database: db/test.sqlite3
          EOS

          redmined bundle install
          redmined bin/rails db:prepare

      - name: Test of basic behaviors
        working-directory: redmine1-src
        run: |
          docker volume ls

          redmined cat /etc/os-release
          redmined bin/about

          redmined printenv | grep RAILS_ENV=test
          redmined printenv | grep PORT=3001

          redmined bin/rails test test/unit/news_test.rb
          redmined bin/rails test test/system/versions_test.rb

      - name: Test of the indivisual settings
        working-directory: redmine1-src
        run: |
          cat <<EOS > .redmined.json
          {
            "default": {
              "name": "default",
              "port": "4000",
              "env": {
                "DEFAULT_ENV": "1"
              }
            },
            "other1": {
              "name": "other1",
              "port": "4001",
              "env": {
                "OTHER1_ENV": "1"
              }
            }
          }
          EOS

          # Test against default
          redmined printenv | grep DEFAULT_ENV=1
          redmined printenv | grep PORT=4000

          # Test against other1
          redmined -n other1 printenv | grep OTHER1_ENV=1
          redmined -n other1 printenv | grep PORT=4001

      - name: Test of multiple execution
        run: |
          cd $GITHUB_WORKSPACE/redmine1-src
          redmined ruby -e "sleep 10" &

          # Wait for container to start
          for _ in $(seq 1 5); do
            if docker ps --format '{{.Names}}' | grep -q "redmined-container-default"; then
              break
            fi
            sleep 1
          done

          docker container ls

          cd $GITHUB_WORKSPACE/redmine2-src
          redmined echo "OK"
